### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by geilsonrm** [cyberhck/omr_javascript#1]
Hello, has this project been finalized? I tried to use it, but to no avail.

**Comment by cyberhck** [comment]
Hi @geilsonrm thanks for showing interest on this project, and I'm sorry to not have replied any sooner, (weekend stuff), please don't use this repo for any purposes, this is a small repo which I tried using where I used to work last time.

There are a lot of other libraries out there which you can use, and I doubt our intention are the same.

This tried to use plain javascript to find marks on a answer sheet, but this repo is incomplete, we ended up creating other repo which unfortunately isn't opensource (believe me, I protested).

If you're trying to find marks on a picture, I'd recommend to use openCV if you are not running your script on a browser, or there are a few javascript libraries as well.
